#!/bin/bash
user=$(whoami)
source ./utils.sh
file=nixpkgs/frio/_user.info.nix
echo "#generated by frio on $(date)
{ 
    username=\"$user\";
    homeDirectory=\"$HOME\";
}" > $file 

if [[ $? -ne 0 ]]; then
    echoError "$file could not be written written"
    exit 1
fi
echoOK "$file written"
