"let g:airline_theme='molokai'
"let g:airline_theme='zenburn'
"let g:airline_theme='lucius'
"let g:airline_theme='onedark'
let g:airline_theme='base16_embers'
"let g:airline_theme='base16_twilight'
"let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
"let g:airline_detect_whitespace=0
let g:airline#extensions#whitespace#enabled = 0
