#!/bin/bash
#
#unset PATH
#source /etc/zshrc

#source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
#source /nix/var/nix/profiles/default/etc/profile.d/nix.sh

#alias sh="$(which dash)"
export LOCALE_ARCHIVE=$HOME/.nix-profile/lib/locale/locale-archive

#bindkey '^p' autosuggest-accept
bindkey '^ ' autosuggest-accept

#WARNING: change this at the user level
export FRG_WS=~/frg/ws
export GPG_TTY=$(tty)

alias runme="nix-shell --pure"

alias log-frago-srv='tail -f -n 500 $FRG_WS/docker/x86/logs/frago.log | ccze -A'
alias log-frago-local='tail -f -n 500 $FRG_WS/docker/x86/logs/frago-local.log | ccze -A'
alias duh='sudo du -h --max-depth=1 | sort -rh'
alias kill-wayland="killall -HUP gnome-shell"
alias tmr="tmux attach"
alias tmk="tmux kill-server"
#alias tmx="tmux -f $ZSH_TMUX_CONFIG"
alias de='nvim -c "cd ~/.config/nixpkgs/" ~/.config/nixpkgs/home.nix'
alias hh='home-manager switch'
alias tmb='tmux kill-session -C'

alias metal="ssh horus@metal"
alias micro="ssh horus@micro"
alias rock="ssh rock@rock"
alias pi="ssh pi@pi"
alias apopos="ssh apophis@popos"
alias bcat='bat --paging=never'
deepfile() { file "$(readlink -f "$(which "$1")")"; }

# Fast parallel compression / decompression using pigz + pv
fastzip() {
    if [ $# -eq 0 ]; then
        echoError "Usage: fastzip <file_or_folder>"
        return 1
    fi
    local target="${1%/}"
    if [ ! -e "$target" ]; then
        echoError "'$target' does not exist"
        return 1
    fi
    local SIZE=$(du -sk "$target" | cut -f1)
    tar cf - "$target" | pv -s ${SIZE}k | pigz -1 -p $(sysctl -n hw.ncpu) > "${target}.tar.gz"
    if [ $? -eq 0 ] && [ -f "${target}.tar.gz" ]; then
        local OUT_SIZE=$(du -sh "${target}.tar.gz" | cut -f1)
        echoOK "Created ${target}.tar.gz (${OUT_SIZE})"
    else
        echoError "Failed to compress '$target'"
        return 1
    fi
}

fastunzip() {
    if [ $# -eq 0 ]; then
        echoError "Usage: fastunzip <file.tar.gz>"
        return 1
    fi
    if [ ! -f "$1" ]; then
        echoError "'$1' is not a file"
        return 1
    fi
    pv "$1" | pigz -d -p $(sysctl -n hw.ncpu) | tar xf -
    if [ $? -eq 0 ]; then
        local EXTRACTED=$(tar tf "$1" 2>/dev/null | head -1 | cut -d'/' -f1)
        if [ -n "$EXTRACTED" ] && [ -e "$EXTRACTED" ]; then
            local OUT_SIZE=$(du -sh "$EXTRACTED" | cut -f1)
            echoOK "Extracted '$EXTRACTED' (${OUT_SIZE})"
        else
            echoOK "Extracted from '$1'"
        fi
    else
        echoError "Failed to decompress '$1'"
        return 1
    fi
}
alias status='git status'
#alias for git commit an passing all arguments to it
alias commit='git commit $@'
alias add='git add $@'

# Alias nix to nix -L to show --print-build-logs and --verbose
alias nix='nix -L'
#If your mc starts slowly, try to disable subshell support, but in your .extra.zshrc
#alias mc="mc --nosubshell"

commitAll() {
    if [ $# -eq 0 ]
        then
            echoError "No arguments supplied"
        else
            git add -A && git commit -am"$1" && git push
    fi
}

makeDefaultShell() {

    local profile=$HOME/.nix-profile/bin
    local nix_zsh=$profile/zsh
    local cmd="chsh -s $nix_zsh"
    local shells=$(cat /etc/shells)
    local zsh=zsh

    if [[ $SHELL != $nix_zsh ]];
        then
            if [[ $shells != *$nix_zsh* ]]; then
                cmd="(echo \"$nix_zsh\" | sudo tee -a /etc/shells) && "$cmd
            fi
            eval $cmd
            echoOK "shell updated, now please logout from shell"
        else
            echoB "$ORANGE""nothing to be done, already you have $BLUE\`$nix_zsh\`$ORANGE as your default shell"

    fi

}

frioCmd() {
    if [ $# -eq 0 ] ;then
        echoError "No arguments supplied"
    elif [[ $1 == 'update' ]]; then
        curl -H 'Cache-Control: no-cache' -L https://raw.githubusercontent.com/frago-io/frio/main/bootstrap.sh | bash
    elif [[ $1 == 'uninstall' ]]; then
        echoB "$ORANGE""uninstall option under construction"
    elif [[ $1 == 'make-default' ]]; then
        makeDefaultShell
    else
        echoError "'$1' option unknown"
        exit 1
    fi
}

alias commit-all=commitAll
alias frio=frioCmd

#NVM
export NVM_DIR="$(echo "$HOME/.nvm")"
#export PATH="$HOME/.cargo/bin:$PATH"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

extraRc=$HOME/.extra.zshrc
if [[ -e "$extraRc" ]]; then source $extraRc; fi

export PATH=$HOME/.yarn/bin:$PATH
export PATH=$HOME/.local/bin:$PATH

#export PATH=$HOME/.nix-profile/bin:/nix/var/nix/profiles/default/bin:$PATH
export PATH=./node_modules/.bin:$PATH

#disable these for zsh tmux plugin
export ZSH_TMUX_CONFIG=
export ZSH_TMUX_FIXTERM=

export EDITOR=nvim;
