#!/bin/bash
#
#unset PATH
#source /etc/zshrc


#alias sh="$(which dash)"
export LOCALE_ARCHIVE=$HOME/.nix-profile/lib/locale/locale-archive

#bindkey '^p' autosuggest-accept
bindkey '^ ' autosuggest-accept

#WARNING: change this at the user level
export FRG_WS=~/frg/ws

alias runme="nix-shell --pure"

alias log-frago-srv='tail -f -n 500 $FRG_WS/docker/x86/logs/frago.log | ccze -A'
alias log-frago-local='tail -f -n 500 $FRG_WS/docker/x86/logs/frago-local.log | ccze -A'
alias duh='sudo du -h --max-depth=1 | sort -rh'
alias kill-wayland="killall -HUP gnome-shell"
alias tmr="tmux attach"
alias tmk="tmux kill-server"
alias de='nvim -c "cd ~/.config/nixpkgs/" ~/.config/nixpkgs/home.nix'
alias hh='home-manager switch'

alias metal="ssh horus@metal"
alias micro="ssh horus@micro"
alias rock="ssh rock@rock"
alias pi="ssh pi@pi"
alias popos="ssh horus@popos"
alias apopos="ssh apophis@popos"
#alias tmux='_zsh_tmux_plugin_run -u'


commitAll() {
    if [ $# -eq 0 ]
        then
            echoError "No arguments supplied"
        else
            git add -A && git commit -am"$1" && git push
    fi
}

makeDefaultShell() {

    local profile=$HOME/.nix-profile/bin
    local nix_zsh=$profile/zsh
    local cmd="chsh -s $nix_zsh"
    local shells=$(cat /etc/shells)
    local zsh=zsh

    if [[ $SHELL != $nix_zsh ]]; 
        then 
            if [[ $shells != *$nix_zsh* ]]; then 
                cmd="(echo \"$nix_zsh\" | sudo tee -a /etc/shells) && "$cmd
            fi
            eval $cmd
            echoOK "shell updated, now please logout from shell"
        else
            echoB "$ORANGE""nothing to be done, already you have $BLUE\`$nix_zsh\`$ORANGE as your default shell"

    fi

}

frioCmd() {
    if [ $# -eq 0 ] ;then
        echoError "No arguments supplied"
    elif [[ $1 == 'update' ]]; then
        curl -H 'Cache-Control: no-cache' -L https://raw.githubusercontent.com/frago-io/frio/main/bootstrap.sh | bash
    elif [[ $1 == 'uninstall' ]]; then
        echoB "$ORANGE""uninstall option under construction"
    elif [[ $1 == 'make-default' ]]; then
        makeDefaultShell
    else
        echoError "'$1' option unknown"
        exit 1
    fi
}

alias commit-all=commitAll
alias frio=frioCmd

#NVM
export NVM_DIR="$(echo "$HOME/.nvm")"
#export PATH="$HOME/.cargo/bin:$PATH"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

extraRc=$HOME/.extra.zshrc
if [[ -e "$extraRc" ]]; then source $extraRc; fi

export PATH=$HOME/.yarn/bin:$PATH
export PATH=$HOME/.local/bin:$PATH

if [ -z "$NIX_PATH" ] && [ -e $HOME/.nix-profile/etc/profile.d/nix.sh ]; 
    then . $HOME/.nix-profile/etc/profile.d/nix.sh; 
fi # added by Nix installer

export PATH=$HOME/.nix-profile/bin:$PATH
export PATH=./node_modules/.bin:$PATH

